### ISSUE TITLE
HU1 - 1 Vista de "Plantillas"

### ISSUE THREAD

**Issue by milo19980525** [udistrital/plantillas_cliente#10]
Se requiere implementar [HU1 - 1](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EZI5GpJBXzpBg2jWJvIXHKABZ_0VTqfxOOH2NlmjqAO8zg?e=J3J97k), relacionada con la visualización inicial de las plantillas para determinado usuario.

**Especificaciones técnicas**

- Actualmente, el último desarrollo se encuentra en la rama develop de cada uno de los proyectos en github (Cliente, mid y crud_serverless).
- El documento con el flujo del módulo de plantillas se encuentra definido en los comentarios del issue: [Flujo y arquitectura de plantillas](https://github.com/udistrital/catalogo_cliente/issues/38)

**Sub Tareas**

- [x] Desarrollar mockup del menú de "Plantillas", submenu "Consultar Plantillas" y la tabla con las plantillas almacenadas en la base de datos.
- [x] Implementar los menús en el API de configuración en entorno de pruebas.
- [x] Revisión de acceso a los menús con base en la configuración realizada en el paso anterior.
- [x] Desarrollo de vista de tabla que carga las plantillas con base en el mockup creado y aprobado.
- [x] Desarrollo de funcionalidad para cargue de plantillas almacenadas en la base de datos (Crud). 

**Criterios de aceptación**

- [x] Se crea el mockup requerido.
- [x] Se evidencia la creación de los menús en el API de configuración en pruebas y en el cliente de plantillas.
- [x] La tabla de las plantillas se carga de manera correcta refelejando lo que existe en la base de datos.
- [x] Se documenta el issue con la respectiva evidencia.

**Requerimientos**

- [x] Deben estar desarrolladas las issues #3, #4, #5 t #9.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by milo19980525** [comment]
@Yaov05 Por favor actualizar estado de desarrollo de la HU.

**Comment by milo19980525** [comment]
@Yaov05 comentar el estado del issue por favor

**Comment by Yaov05** [comment]
Para esta tarea se desarrolló la tabla de vista de plantillas como un componente individual. Actualmente en pruebas surge un inconveniente al crear la aplicación para crear el menú en configuración. Se encuentra creada la aplicación en producción.

**Comment by Yaov05** [comment]
![image](https://github.com/udistrital/plantillas_cliente/assets/42217637/582b7865-479c-4268-a621-45b4f4c6e118)


Para la HU1 se usa un rol, correspondiente al encargado de jurídica

![image](https://github.com/udistrital/plantillas_cliente/assets/42217637/a3e801ba-6dfd-4fc3-bacd-36706bcd53e0)

**Comment by Yaov05** [comment]
A continuación, se muestra el boceto de la tabla de consulta de plantillas.

![image](https://github.com/udistrital/plantillas_cliente/assets/42217637/06ff481f-9c0c-48c5-99dc-539e57f4eec9)


En este momento se está solucionando un inconveniente al mostrar los íconos de las acciones, ya que se muestra el nombre de la acción en su lugar

(Esta es una muestra de la tabla de visualización de novedades, la página no se vería así, pero a falta del menú en pruebas, se muestra el componente aislado)

**Comment by Yaov05** [comment]
![image](https://github.com/udistrital/plantillas_cliente/assets/42217637/a065dceb-4826-4715-89e2-3b4cc1065fba)

**Comment by milo19980525** [comment]
@Yaov05 falta crear los respectivos menús en configuración (pruebas).

![image](https://github.com/udistrital/plantillas_cliente/assets/106636533/b3ea4f2f-cfc8-46d0-a643-315ac386146a)

**Comment by milo19980525** [comment]
@Yaov05 por favor insertar los menús con usuario pruebasoas1.

**Comment by Yaov05** [comment]
![image](https://github.com/udistrital/plantillas_cliente/assets/42217637/94155867-ca59-4500-a2cd-c46737c9a335)

**Comment by Yaov05** [comment]
Registro en BD:

![image](https://github.com/udistrital/plantillas_cliente/assets/42217637/a55693bb-d619-4a1c-b781-afdae60f9118)

Petición del cliente:

![image](https://github.com/udistrital/plantillas_cliente/assets/42217637/9dc8991e-9bad-4d12-ba08-1ed745d99ff7)

**Comment by milo19980525** [comment]
Perfecto, con el servicio de conversión del mid como queda armado el PDF?

**Comment by milo19980525** [comment]
Inicialmente se cierra la tarea dado que la conversión se trata en el issue #13
