### ISSUE TITLE
Documento Diagnóstico Final

### ISSUE THREAD

**Issue by milo19980525** [udistrital/plantillas_cliente#12]
Se requiere realizar el documento final "Diagnóstico" para todos las funcionalidades desarrolladas y por desarrollar en Plantillas.

**Especificaciones técnicas**

- El formato del informe diagnóstico se encuentra en: https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EcEzaU-TYfNMpdLTB7j9u5IB-pa9uKfFzPSdI-ANpHqThA?e=1l6H4s.

**Sub Tareas**

- [x] Con base en el formatos propuesto desarrollar el informe.

**Criterios de aceptación**

- [x] Se genera un diagnóstico final sobre los proyectos llevados a cabo en Plantillas.

**Requerimientos**

- [X] Formato para desarrollar.

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Yaov05** [comment]
Documento diagnóstico:
https://udistritaleduco-my.sharepoint.com/:w:/g/personal/yaortizv_udistrital_edu_co/Ebr7GOycX_tGg8nVW7pTZyQBia2qR54ahn7MVUOZIbQdMA?e=Pyhlfp

**Comment by milo19980525** [comment]
@Yaov05 buen trabajo, dejar por favor el ítem de tutoriales y hacer la anotación que no se cuenta con estos.

En cuanto a plan de mejoramiento se debe mencionar los hitos o funcionalidades pendientes por desarrollar, puede ser una guía: 
https://github.com/udistrital/catalogo_cliente/issues/38
