### ISSUE TITLE
Revisión y ajuste de la base de datos de Plantillas

### ISSUE THREAD

**Issue by milo19980525** [udistrital/plantillas_cliente#13]
Se requiere revisar de manera minuciosa el desarrollo de pllantillas CRUD y con esto la base de datos del módulo de plantillas, con el propósito de ajustar el modelo para que permita almacenar un solo tipo de documento (HTML).

**Especificaciones técnicas**

- Actualmente, el último desarrollo se encuentra en la rama develop de plantillas_crud_serverless.
- El documento con el flujo del módulo de plantillas se encuentra definido en los comentarios del issue: [Flujo y arquitectura de plantillas](https://github.com/udistrital/catalogo_cliente/issues/38)

**Sub Tareas**

- [x] Teniendo en cuenta la reunión relaizada con el equipo de SGA, se debe realizar una inspección al modelo de la base de datos no relacional definida en #2, dado que se sugirió que no solo se almacenaran documentos PDF si no cualquier tipo de plantilla.
- [x] Se determina como estrategia candidata, almacenar un documento HTML e internamente en el caso de plantillas se debe implementar un servicio que convierta ese HTML en PDF (MID), por lo que el tratamiento de campos dinámicos debe ser realizado mediante una etiqueta o carácter especial.
- [x] Con base en la estructura definida en el modelo corregido, los controladores del API CRUD deben ajustarse.

**Criterios de aceptación**

- [x] Se evidencia el modelo de datos ajustado a las necesidades expuestas.
- [x] Se ajusta la base de datos al modelo propuesto.
- [x] Se modifican los controladores para que respondan al nuevo esquema planteado.
- [x] Se documenta el issue con la respectiva evidencia.

**Requerimientos**

- [x] Deben estar desarrolladas las issues #3, #4, #5, #9 y 10.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by milo19980525** [comment]
@Yaov05 comentar el estado del issue por favor

**Comment by Yaov05** [comment]
Al optarse por almacenar la plantilla en formato html en la BD, el modelo se reduce a la colección "Plantilla" con su correspondiente campo de contenido.

![image](https://github.com/udistrital/plantillas_cliente/assets/42217637/6d33b174-0df9-4df4-be34-566026d446b4)

**Comment by milo19980525** [comment]
@Yaov05 Por favor subir el código ajustado, las sentencias de adecuación de las colecciones.

**Comment by Yaov05** [comment]
En el siguiente script se encuentra una sentencia sencilla para eliminar la base de datos anteriormente creada, referenciarla nuevamente usando el comando "use" y registrar un primer documento para crear la colección y la base de datos de nuevo:

[BD_Plantillas (2).txt](https://github.com/udistrital/plantillas_cliente/files/13718359/BD_Plantillas.2.txt)

**Comment by milo19980525** [comment]
@Yaov05 subir el código a develop por favor.

**Comment by Yaov05** [comment]
Commits:

https://github.com/udistrital/plantillas_crud_serverless/commit/1646a697fd8e7c8098e6a6aa134a33d21e6f4cd0

https://github.com/udistrital/plantillas_crud_serverless/commit/9d103f706133d40d748b7f39772327798b061133
