### ISSUE TITLE
H1 - 2 Filtrado de plantillas

### ISSUE THREAD

**Issue by milo19980525** [udistrital/plantillas_cliente#14]
Se requiere implementar [HU1 - 2](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EZI5GpJBXzpBg2jWJvIXHKABZ_0VTqfxOOH2NlmjqAO8zg?e=J3J97k), relacionada con el filtrado de plantillas registradas en el aplicativo.

**Especificaciones técnicas**

- Actualmente, el último desarrollo se encuentra en la rama develop de cada uno de los proyectos en github (Cliente, mid y crud_serverless).
- El documento con el flujo del módulo de plantillas se encuentra definido en los comentarios del issue: [Flujo y arquitectura de plantillas](https://github.com/udistrital/catalogo_cliente/issues/38)

**Sub Tareas**

- [x] A la vista desarrollada en #10 debe aplicar los filtros por tipo de documento, identificación, fecha de creación, nombre y fecha de última modificación

**Criterios de aceptación**

- [x] Se evidencia la posivilidad de utilizar filtros para recuperar aquellas plantillas requeridas por el usuario.
- [x] Se documenta el issue con la respectiva evidencia.

**Requerimientos**

- [x] Deben estar desarrolladas las issues #3, #4, #5, #9 y 10.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by milo19980525** [comment]
@Yaov05 comentar el estado del issue por favor

**Comment by Yaov05** [comment]
Se aplica algunas funcionalidades a la tabla de visualización de plantillas:

- Al dar click en el nombre del campo, se ordenan los registros según ese campo en orden alfabético ascendente o descendente.
- Paginación (4 registros en la imagen)

![image](https://github.com/udistrital/plantillas_cliente/assets/42217637/30a11b01-b91f-4502-b2ea-7712c41e6add)

![image](https://github.com/udistrital/plantillas_cliente/assets/42217637/1837d5c4-57c3-4c67-9db2-7f62a05c609d)

- Se puede filtrar por uno o varios campos, escribiendo palabras clave.

![image](https://github.com/udistrital/plantillas_cliente/assets/42217637/6443c0fe-685e-42a9-bb30-0e63075e6c01)

- Es posible seleccionar uno, varios o todos los registros para realizar acciones con ciertos registros al mismo tiempo.

![image](https://github.com/udistrital/plantillas_cliente/assets/42217637/5f004bbf-c825-4f32-b743-9137cb8d7e10)

**Comment by milo19980525** [comment]
@Yaov05 por favor subir el avance respectivo a esta tarea y la anterior al repo del cliente (develop).

**Comment by Yaov05** [comment]
El desarrollo respectivo se encuentra en el commit: https://github.com/udistrital/plantillas_cliente/commit/9f22f4c9f1178970c548cec62a570cd915285caf
