### ISSUE TITLE
Análisis, diseño, construcción y creación de BD para módulo de plantillas

### ISSUE THREAD

**Issue by a52290451** [udistrital/plantillas_cliente#2]
Se requiere realizar el análisis, diseño, construcción y creación de la Base de Datos necesaria para soportar el almacenamiento de información del módulo de plantillas.

**Especificaciones técnicas**

- Se adjunta como soporte el diagrama de flujo de actividades del modulo de plantillas.
- La base de datos debe soportar el almacenamiento de: https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/Efy5WGMmwD5IuF9GaqgSIEEBJ1nBFtnJmJM5NnpmCmZiIw?e=vcm3J4
1. Plantillas.
2. Secciones.
3. Minutas.
4. Títulos.
5. Imágenes.
6. Campos dinámicos (listado).
7. Especificaciones de estilo por cada elemento.
8. Historial de versiones (relación entre plantillas por registro).
9. Estado de una plantilla.
10. Información de creación de una plantilla (fecha de creación, fecha de última modificación, etc...).
11. Enlace a documento físico de la plantilla.
- La creación de la base de datos debe realizarse mediante scripts y ejecutarse a través de beego migrate desde el API CRUD.

NOTA: se deben tener en cuenta las relaciones entre elementos de una plantilla y su orden de aparición.

**Sub Tareas**

- [x] Análisis de información requerida a ser almacenada en la nueva BD de plantillas.
- [x] Diseño del modelo de BD para el módulo de plantillas.
- [x] Aprobación del diseño de de BD para el módulo de plantillas
- [x] Construcción de scripts para creación de BD.
- [x] Creación de BD a través de beego migrate, mediante el API CRUD, en local y ambiente de pruebas.

**Criterios de aceptación**

- [x] Se identifican toda la información requerida a ser almacenada en la BD del modulo de plantillas.
- [x] Se especifican y organizan lógicamente los campos y tablas necesarios para almacenar dicha información en la BD, a través de un modelo de datos.
- [x] El modelo de datos es aprobado por DBAs y Arquitecto.
- [x] Se construyen los Scripts necesarios para la creación de la BD.
- [x] La BD se encuentra creada en ambiente local y en ambiente de pruebas.

**Requerimientos**

- No presenta.

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by milo19980525** [comment]
@Yaov05 Por favor subir el análisis y modelo de datos realizado.

**Comment by Yaov05** [comment]
Para el modelo de datos se propone el siguiente modelo:

![image](https://github.com/udistrital/plantillas_cliente/assets/42217637/0b10aab6-f2c7-47d6-9842-977bfbc969e1)

para este caso, se tienen inscrustadas las colecciones de secciones, minutas, títulos e imágenes en la de Plantilla, y estas están conectadas a la colección de estilos de fuente, que es el campo que puede ser actualizado de manera más frecuente.

Aun así, se contempla la posibilidad de manejar esta misma relación con las colecciones mencionadas anteriormente, en caso de que una sección, minuta o título pueda usarse en más de una plantilla, para reducir la carga de procesamiento, al momento de actualizar la información de las mismas.

Los campos dinámicos pueden ser agregados en cualquiera de las anteriores colecciones

Actualmente se está terminando el modelo en su versión relacional, en PGModeler para hacer la comparación y seguir la arquitectura propuesta en el diagrama de flujo de actividades.

**Comment by Yaov05** [comment]
![Modelo](https://github.com/udistrital/plantillas_cliente/assets/42217637/b85e3485-02b9-4647-8848-f07c5252b9a9)

**Comment by milo19980525** [comment]
Se determina como mejor modelo de base de datos para el ejercicio de plantillas el modelo no relacional a ser implementado en MongoDB.

**Comment by milo19980525** [comment]
@Yaov05 por favor comentar con la creación de la base de datos en local.

**Comment by Yaov05** [comment]
Se crea manualmente la base de datos en local para hacer pruebas de inserción, modificación y eliminación de los datos

![image](https://github.com/udistrital/plantillas_cliente/assets/42217637/1dd0ada1-8d2c-4fa2-91f6-fcc5ed2871d8)

**Comment by Yaov05** [comment]
Código para la creación de la base de datos en local (Usando el shell de MongoDB)
[BD_Plantillas.txt](https://github.com/udistrital/plantillas_cliente/files/12639766/BD_Plantillas.txt)
