### ISSUE TITLE
Creación de API plantillas_crud

### ISSUE THREAD

**Issue by a52290451** [udistrital/plantillas_cliente#3]
Se requiere crear en su forma base el API plantillas_crud para el modulo de plantillas.

**Especificaciones técnicas**

- El repositorio del API es: https://github.com/udistrital/plantillas_crud

**Sub Tareas**

- [x] Creación y ajuste del repositorio.
- [x] Creación de API en local, con estructura base de API CRUD (tomar como referencia el API cumplidos_dve_crud en sus primeros commits).
- [x] Adecuación de API CRUD para conectar con la BD de plantillas.
- [x] Aplicación de lineamientos para creación de API CRUD.

**Criterios de aceptación**

- [x] El API se encuentra creada y contiene todos los controladores requeridos para conectar con la BD.
- [x] El API cumple con los [lineamientos](https://github.com/udistrital/lineamientos_oas) dispuestos para la creación de un API CRUD.

**Requerimientos**

- [x] EL issue #2 , debe estar terminado.
- [x] El repositorio plantillas_crud debe estar creado.

**Dependencias**

- No presenta

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by milo19980525** [comment]
@Yaov05 por favor comentar el issue.

**Comment by Yaov05** [comment]
Se adjunta el primer commit del api crud: https://github.com/udistrital/plantillas_crud/commit/37cec2c4429de9b60b321b199a98a55315402a1c


Por el momento hacen falta los archivos de ejecución del api en los distintos ambientes (Dockerfile, drone, swagger)

**Comment by milo19980525** [comment]
@Yaov05 Según lo comentado el día de ayer y hoy falta subir un commit con nuevos controladores, por favor documentar la issue con dichos cambios.

**Comment by Yaov05** [comment]
Commit con los cambios a controladores y flujo por servicios:
https://github.com/udistrital/plantillas_crud/commit/3cb6753ace61e1fb12fcd0ffdada1ab187efb168
