### ISSUE TITLE
Adaptación de plantillas_cliente a nueva arquitectura de MFs - PARTE 2

### ISSUE THREAD

**Issue by a52290451** [udistrital/plantillas_cliente#30]
Se requiere llevar a cabo la adaptación del cliente de plantillas para que cumpla con los lineamientos dispuestos para la nueva arquitectura de MFs.

**Especificaciones Técnicas**

- De acuerdo con los lineamientos, se requiere ajustar todo el cliente de plantillas_cliente, para que presente las vistas y modulos de forma dínamica en microfrontends.
- Los microfrontends deben ser creados de acuerdo con lo dispuesto en udistrital/plantillas_cliente#34 .
- Cada arquitectura de nuevos sistemas en el apartado de clientes, debe cumplir como minimo con: **root_mf**, **core_mf** y **pantillas_mf**.
- Debe darse la conexión requerida entre MFs para que se pueda acceder como un solo cliente.

**Sub Tareas**

- [x] Ajuste de arquitectura de plantillas_cliente a MFs.
- [x] Conexión entre MFs.
- [x] Prueba de funcionalidades y menus de la nueva arquitectura.

**Criterios de aceptación**

- [x] Se presenta el módulo de plantillas en la nueva arquitectura de MFs, dispuesta para nuevos clientes, completamente funcional.

**Requerimientos**

No presenta

**Dependencias**

- plantillas_cliente.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
Se requiere adjuntar link de capacitación

**Comment by a52290451** [comment]
Single SPA

**Comment by a52290451** [comment]
@Oscarjaimes1710 subir estado de la actividad

**Comment by Oscarjaimes1710** [comment]
Se requiere La creacion de dos repositorios , root_mf_plantillas y core_plantillas

**Comment by a52290451** [comment]
Creación plantillas_root_mf: https://github.com/udistrital/plantillas_root_mf

Por favor subir código al repositorio señalado

Para el CORE, se deberá realizar la conexión con: [core_mf_cliente](https://github.com/udistrital/core_mf_cliente)

**Comment by a52290451** [comment]
Subir evidencia de avances por favor

**Comment by Oscarjaimes1710** [comment]
Queda pendiente la aprobación de @a52290451 del root de plantillas relacionado en el siguiente commit : https://github.com/udistrital/plantillas_root_mf/commit/6991b206ded97a8384ba7df232118b21ea1e05e2
