### ISSUE TITLE
Propuesta nuevo modelo de datos Plantillas

### ISSUE THREAD

**Issue by a52290451** [udistrital/plantillas_cliente#33]
Se requiere realizarla propuesta de un nuevo modelo de datos, tomando como base lo implementado en https://github.com/udistrital/plantillas_cliente/issues/2.

El modelo de datos debe soportar las funcionalidades descritas en: https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/Efy5WGMmwD5IuF9GaqgSIEEBJ1nBFtnJmJM5NnpmCmZiIw?e=oVQwev

**Aspectos técnicos**

- Se debe proponer un modelo de datos relacionas y otro no relacional. Ambos deben cubrir las necesidades y funcionalidades descritas en el diagrama de flujo de Plantillas.

**Sub Tareas**

- [x] Propuesta modelo de datos relacional.
- [x] Propuesta modelo de datos no relacional.

**Criterios de aceptación**

- [x] Se propone un modelo de datos relacional que soporta todas las funcionalidades de plantillas.
- [x] Se propone un modelo de no datos relacional que soporta todas las funcionalidades de plantillas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
@Oscarjaimes1710 por favor carga evidencia del estado de la issue

**Comment by Oscarjaimes1710** [comment]
se comparte link  de la propuesta del modelo de plantillas de acuerdo con lo hablado en los Daily: https://miro.com/welcomeonboard/VWpOZDJLU3FYcEN4RVJLaWlsSDFBeVkzSEc3MllEZFBWU2F3YjNkY0tNNzduU0ZVcFBlZUk4TVZOVHJlTmxnanwzNDU4NzY0NTk2Mzc2NzYwMzc3fDI=?share_link_id=359898979683

se deja evidencia grafica 
<img width="1134" alt="Captura de pantalla 2024-08-05 a la(s) 7 31 31 p  m" src="https://github.com/user-attachments/assets/976332f3-9ee4-4537-bf0a-e1165820e4f7">

se realiza una propuesta del modelo teniendo en cuenta los siguientes aspectos:
1. El campo contenido hace referencia a los contenidos de la plantilla,dividido en tres secciones las cuales son encabezado, contenido y pie de pagina, cada una de estas con sus respectivos estilos.También en está colección se encuentra el campo imagen y el tamaño imagen, con el fin de tener las propiedades que el usuario selecciona.
2. En la colección principal encontraremos el campo llamado id_padre para hacer referencia a la versión anterior .Esto se basa en las reuniones tenidas en los Daily, se define que la forma mas pertinente de llevar las versiones anteriores de las plantillas es que la nueva versión de la plantilla herede el campo primario de la versión anterior convirtiendo así en la llave foránea.
3. El campo dependencia plantilla se basa en el sistema desde el cual se solicita la plantilla, ejemplo:financiera,jurídica, oas,etc.
4.El campo tipo plantilla hace referencia al tipo de la plantilla que se desee usar ejemplo: contratos, certificaciones,etc.

**Comment by Oscarjaimes1710** [comment]
Se hacen los ajustes solicitados por parte del lider, a falta de una revision puntual de la coleccion que contendra el contenido en forma de arbol de la plantilla.
![Captura de pantalla 2024-08-06 a la(s) 8 07 50 p  m](https://github.com/user-attachments/assets/0761aa4a-d26a-4f0a-acd4-29c13bc7c417)

**Comment by Oscarjaimes1710** [comment]
![Captura de pantalla 2024-08-09 a la(s) 5 17 08 p  m](https://github.com/user-attachments/assets/ab3bacbe-d58b-48b3-8f6d-e866fc68117e)

Se hacen unos ajustes solicitados por el líder @a52290451 entonces el modelo quedaría así como se muestra en la imagen: 
1. Sistema corresponde a la colecciones de sistemas/dependencias desde los cuales vendrán las solicitudes de plantillas.
2. Tipo_plantilla corresponde a los tipos de documento que cada sistema/dependencia pueda solicitar para generar plantilla.
3. La referencia de Id_padre a Id_plantilla hace referencia a que toda plantilla deberá tener un padre para hacer referencia a la versión si su Id_padre es el mismo Id_plantilla entonces esa plantilla es la versión 1 , el documento original. 
4. El desglose en árbol de contenido plantilla, hace referencia a que el contenido se debe distribuir en forma de árbol y se divine en un contenido_plantilla posteriormente ese contenido puede tener 1 o mas tipos de contenido(texto, imagen). También el contenido podrá contener n cantidad de secciones cada una con sus estilos propios , títulos entre otros. 
5. Cada plantilla contendrá campos dinámicos que serán listados y validados. 
6. Los estilos son un arreglo de tipo clave valor.

**Comment by Oscarjaimes1710** [comment]
![Captura de pantalla 2024-08-11 a la(s) 10 25 08 a  m](https://github.com/user-attachments/assets/09032a0c-ca15-42e0-ab97-7b0f4e3a6d04)

Ajuste solicitado , realizado.

**Comment by a52290451** [comment]
Se realizan las siguientes observaciones sobre el modelo de datos:

1. No existe relación entre tipo_plantilla y sistemas.
2. La colección "sistemas" debe cambiar su nombre por "sistema".
3. Se debe corregir el campo "conetido_plantilla_id" por "contenido_id" en "Plantillas".
4. La colección "contenido desaparece, en su lugar se debe crear en plantillas el campo "secciones" que es un arreglo en donde están todas las secciones.
5. El campo Estado_plantilla debe cambiar por estado en "Plantillas".
6. Se debe corregir y ajustar el uso de mayúsculas y minúsculas.
7. El nombre de la colección "Plantillas" debe cambiar por "Plantilla".
8. Se debe cambiar el nombre "secciones" por "seccion".
9. se debe eliminar la referencia a "contenido" o en su defecto a "plantilla" de la colección "seccion".

Queda pendiente definir con el equipo tecnico la forma correcta de utilizar los "Campos dinamicos".

**Comment by a52290451** [comment]
@Oscarjaimes1710 de acuerdo a lo señalado en revisión, por favor subir ajustes finales

**Comment by Oscarjaimes1710** [comment]
![Captura de pantalla 2024-08-14 a la(s) 9 00 47 a  m](https://github.com/user-attachments/assets/1f4269d6-f020-4218-9da0-55a94f77fcd2)

Url: https://drive.google.com/file/d/1iS40icXPITUXtLBDJ5V-KRWUvwiBe7Jb/view?usp=sharing 
Modelo ajustado según lo solicitado.

**Comment by Oscarjaimes1710** [comment]
![plantillas final drawio](https://github.com/user-attachments/assets/0a0dc91c-293c-498a-baef-48dda4d927ce)

**Comment by a52290451** [comment]
Se valida modelo de datos para plantillas.

**Comment by Oscarjaimes1710** [comment]
![Captura de pantalla 2024-08-15 a la(s) 4 55 53 p  m](https://github.com/user-attachments/assets/87da10f8-f118-41a2-b05b-e82b88c90f19)

Version final del modelo de plantillas. 

Editable : https://drive.google.com/file/d/1iS40icXPITUXtLBDJ5V-KRWUvwiBe7Jb/view?usp=sharing

**Comment by a52290451** [comment]
Queda pendiente aprobación Equipo de DBAs

**Comment by Oscarjaimes1710** [comment]
Modelo con los ajustes solicitados por el equipo de DBAs.

<img width="720" alt="Captura de pantalla 2024-08-21 a la(s) 5 13 48 p  m" src="https://github.com/user-attachments/assets/b91b01b2-ee06-4fc6-865b-1d9c9aad5685">

**Comment by Oscarjaimes1710** [comment]
Ajustes Finales Modelo final. 
Editable: https://drive.google.com/file/d/1iS40icXPITUXtLBDJ5V-KRWUvwiBe7Jb/view?usp=sharing
![Captura de pantalla 2024-08-21 a la(s) 8 11 50 p  m](https://github.com/user-attachments/assets/958db9b0-f517-400a-8921-8a07e7c8bd95)

**Comment by a52290451** [comment]
Se valida y aprueba modelo de datos.
