### ISSUE TITLE
Propuesta de Arquitectura - Módulo de plantillas.

### ISSUE THREAD

**Issue by a52290451** [udistrital/plantillas_cliente#34]
Se requiere realizar el diagrama de componentes del modulo de plantillas, en el cual se refleje su arquitectura a nivel de microservicios y micro clientes, de tal forma que cada uno sea independiente, autosuficiente, escalable, resiliente y tolerante a fallos.

El objetivo es presentar una arquitectura que desacople las funcionalidades del módulo y descentralice los servicios de forma lógica para que sea mas sencillo realizar mantenimiento en los mismos y facilitar tareas de intervención por parte del equipo de desarrollo.

**Especificaciones técnicas**

- Cada Microservicio debe estar conformado por el conjunto de servicios que se relacionen funcionalmente.
- Dependiendo de las funcionalidades del microservicio, cada uno debe consumir la BD que requiera.
- Cada Microservicio debe ser descentralizado, lo cual implica que debe poder ser desarrollado, implementado y escalado de forma independiente de otros.

**Material de apoyo**

- [Link de actividad guía para la implementación del diagrama de componentes.](https://github.com/udistrital/planeacion_cliente/issues/803)

**Sub Tareas**

- [x] Creación de diagrama de componentes de la arquitectura propuesta para el módulo de plantillas, con base en el diagrama de flujo.
- [x] Creación de listado de Microservicios a detalle, señalando las funcionalidades que lo conforman, así como su relación con otros microservicios y componentes de la OATI.

**Criterios de aceptación**

- [x] El diagrama de componentes muestra la división clara del sistema en múltiples microservicios y su relación con los diferentes componentes de la OATI para su funcionamiento.
- [x] El detalle de los microservicios, muestra el listado de funcionalidades que componen cada microservicio y que relación existe entre cada uno de los microservicios entre si y con otros componentes de la OATI.

**Requerimientos**

- No presenta.

Dependencias

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
@Oscarjaimes1710 se requiere actualización del estado de esta issue

**Comment by Oscarjaimes1710** [comment]
Actualmente se esta empezando a plasmar los modelos de arquitectura de plantillas tanto el modelo general como el del cliente y el mid 
![Captura de pantalla 2024-08-09 a la(s) 7 19 44 p  m](https://github.com/user-attachments/assets/3b559cbc-ceb9-4196-a415-35a789939f04)

**Comment by a52290451** [comment]
@Oscarjaimes1710 se requiere cargar evidencia del avance en cada caso

**Comment by Oscarjaimes1710** [comment]
![Captura de pantalla 2024-08-12 a la(s) 7 53 53 p  m](https://github.com/user-attachments/assets/f07d3c72-e14d-44e6-9848-5f5d3c861476)

Basado en el análisis previamente hecho se llega a la conclusión que solamente se necesita un micro-servicio y se plasma así por ahora.

**Comment by a52290451** [comment]
@Oscarjaimes1710 de acuerdo a lo señalado en revisión, por favor subir ajustes finales

**Comment by Oscarjaimes1710** [comment]
![Captura de pantalla 2024-08-13 a la(s) 7 04 25 p  m](https://github.com/user-attachments/assets/73171e94-b321-4533-9a48-eff1a20e7352)

Se hacen ajustes requeridos y se carga para revisión.

**Comment by a52290451** [comment]
@Oscarjaimes1710 De acuerdo a lo discutido en el daily, se requiere subir ajustes relacionados.

**Comment by Oscarjaimes1710** [comment]
![Plantillas_estruc drawio](https://github.com/user-attachments/assets/ef8695e4-512f-41d3-8c73-ca50be4e9267)

Este es el modelo ajustado con todos las correcciones dictadas por los lideres y en consecuencia a unir este proceso con lo ya desarrollado por el equipo de Heiner.

**Comment by Oscarjaimes1710** [comment]
![Captura de pantalla 2024-08-15 a la(s) 3 00 49 p  m](https://github.com/user-attachments/assets/ce457e3f-a9ba-4e87-88ad-8183246bf453)

Actualmente se trabaja en una versión un poco mas vistosa.
Se hacen los ajustes pequeños solicitados , a falta de confirmación para cargar el editable final.

**Comment by a52290451** [comment]
@Oscarjaimes1710 por favor compartir editable de la arquitectura.

**Comment by Oscarjaimes1710** [comment]
Con los ajustes solicitados aqui esta el editable de la arquitectura y una imagen de la arquitectura definitiva. 

- https://drive.google.com/file/d/1gCN1bnYkvz74DjhaJepVygTuIRgV5ilF/view?usp=sharing

<img width="897" alt="Captura de pantalla 2024-08-16 a la(s) 6 44 19 p  m" src="https://github.com/user-attachments/assets/654bb0b7-ad8b-41a2-9b5a-24a49a637060">

**Comment by Oscarjaimes1710** [comment]
Conclusión Final: La propuesta de arquitectura considera el estado actual del cliente de plantillas y el desarrollo gestionado por el equipo de Heiner. Se incorpora la lógica establecida, que incluye el renderizado de plantillas durante la previsualización y generación de documentos. La arquitectura define la implementación de un microcliente y un micromid, que interactúan con un microservicio externo y tres CRUDs dinámicos, como se detalla en el diseño arquitectónico. En resumen, se integran todos los ajustes derivados del nuevo modelo de plantilla y el desarrollo actual realizado por el equipo de Heiner.

**Comment by a52290451** [comment]
@Oscarjaimes1710 Se requiere realizar ajuste final de la arquitectura, de acuerdo a las observaciones realizadas.

**Comment by Oscarjaimes1710** [comment]
Arquitectura ajustada a lo solicitado.
Editable: https://drive.google.com/file/d/1gCN1bnYkvz74DjhaJepVygTuIRgV5ilF/view?usp=sharing
![Captura de pantalla 2024-08-21 a la(s) 5 25 11 p  m](https://github.com/user-attachments/assets/506ba2e3-ff4e-4168-84a8-503a5b8fe07c)

**Comment by a52290451** [comment]
![Image](https://github.com/user-attachments/assets/5456b61b-22c3-4768-bf9d-dc2e3f670d23)

**Comment by a52290451** [comment]
Se finaliza Actividad.

**Comment by norbeydanilo** [comment]
Ejemplo de [documento/diagrama de SGA](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/ETKXN4aYc_9OtInCD8A3zp0BKsWLM0b5FGl7FYpa7250vg?e=5x9Ebu)

**Comment by Oscarjaimes1710** [comment]
Resumen: Se hace lo pedido por el lider @a52290451 y por el ingeniero @norbeydanilo , a la espera de retroalimentación va quedando así: 

![Captura de pantalla 2024-08-30 a la(s) 10 36 18 p  m](https://github.com/user-attachments/assets/5fda980b-9be6-496f-acb8-85df44357666)


Editable : https://drive.google.com/file/d/1IE9jScUpv3iK4e_P19Ugc04gyAS6sytm/view?usp=sharing

**Comment by Oscarjaimes1710** [comment]
![Captura de pantalla 2024-09-04 a la(s) 6 15 41 p  m](https://github.com/user-attachments/assets/8d43c926-266b-4ac4-b680-003da5099055)
Ajustes realizados según lo solicitado.

**Comment by Oscarjaimes1710** [comment]
Ajuste final a falta de ultima revisión por parte de el líder @a52290451 
![Captura de pantalla 2024-09-04 a la(s) 8 18 49 p  m](https://github.com/user-attachments/assets/5b0bf5df-e343-4f3e-851a-e49044e84e4d)

**Comment by Oscarjaimes1710** [comment]
![Captura de pantalla 2024-09-20 a la(s) 6 38 21 p m](https://github.com/user-attachments/assets/75136716-d122-4960-a8a4-4fe8b9a3a2e0)



Nueva arquitectura ajustada con todos los cambios que han surgido en el proceso.

**Comment by Oscarjaimes1710** [comment]
https://drive.google.com/file/d/1gCN1bnYkvz74DjhaJepVygTuIRgV5ilF/view?usp=sharing

**Comment by Oscarjaimes1710** [comment]
<img width="913" alt="Captura de pantalla 2024-09-21 a la(s) 9 32 49 a m" src="https://github.com/user-attachments/assets/9144eb6e-aec8-40ff-8666-8324d8d68b63">
