### ISSUE TITLE
Análisis y Construcción de base de datos - P1

### ISSUE THREAD

**Issue by a52290451** [udistrital/plantillas_cliente#37]
Se requiere llevar a cabo el análisis y construcción de la base de datos de plantillas, de acuerdo con el modelo de datos propuesto en udistrital/plantillas_cliente#33 .

**Especificaciones Técnicas**

- Se requiere llevar a cabo un análisis de rendimiento y de costos acerca de la infraestructura necesaria para implementar el modelo de datos. Este puede desarrollarse en Bases de datos relacionales o no relacionales, empleando una API CRUD para acceder a los datos, o utilizar serverless en AWS.
- Una vez realizado el análisis y elegida la infraestructura adecuada, se requiere realizar la implementación del modelo de datos.
- La base de datos debe cumplir con los lineamientos definidos por la OATI.

**Sub Tareas**

- [x] Análisis de implementación de BD.

**Criterios de aceptación**

- [x] Se elige correctamente la infraestructura sobre la cual se implementará el modelo de datos.

**Requerimientos**

No aplica

**Dependencias**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Oscarjaimes1710** [comment]
Local con VPN de OATI:

-Seguridad y Control: Ofrece mayor control sobre los datos y cumple con los lineamientos de seguridad de OATI. Es ideal si se requiere un entorno con alta seguridad y conformidad regulatoria.

-Costo: Implica costos iniciales más altos en infraestructura y mantenimiento, pero puede ser más económico a largo plazo si el volumen de datos y accesos es constante.

-Escalabilidad: Limitada a la capacidad del hardware disponible, lo que podría requerir actualizaciones costosas en el futuro.

Serverless en AWS:

-Flexibilidad y Escalabilidad: AWS serverless permite escalabilidad automática y flexibilidad, ideal para aplicaciones con demanda variable. Paga solo por el uso, lo que puede ser más económico a corto plazo.

-Mantenimiento: AWS gestiona la infraestructura, liberando al equipo de TI de tareas de mantenimiento. Esto permite enfocarse en el desarrollo y la optimización de aplicaciones.

-Seguridad y Cumplimiento: AWS cumple con estándares de seguridad internacionales, pero es crucial asegurarse de que también cumpla con los requisitos específicos de OATI.

-Desventajas: Costos variables a largo plazo, dependencia del proveedor, cumplimiento de políticas de seguridad específicas.

**Comment by Oscarjaimes1710** [comment]
Serverless en AWS:

-Qué es: Serverless es un modelo de computación en la nube en AWS que permite ejecutar aplicaciones sin gestionar servidores. AWS maneja automáticamente la infraestructura, escalabilidad y disponibilidad.
Todo se maneja con LAMBDA's.

-Funcionamiento: Las aplicaciones o bases de datos se ejecutan bajo demanda y se escalan automáticamente según el tráfico. Solo pagas por el tiempo de ejecución y los recursos consumidos.

Capacidad de Respuesta:

-Accesos y Velocidad: Altamente escalable y rápido, con tiempos de respuesta que pueden ser milisegundos. Ideal para aplicaciones con fluctuaciones en el tráfico.

¿Por qué Serverless?:

-Sí: Si necesitas escalabilidad, flexibilidad y no quieres preocuparte por la infraestructura, serverless es ideal.

-No: Si necesitas un control estricto, seguridad específica, o predecir con precisión los costos, podría no ser la mejor opción. Adicional si las peticiones son constantes el costo se puede AUMENTAR bastante. 

¿Por qué en API con Servidor?

Sí:
-Control y Seguridad: Ofrece control total sobre la infraestructura y datos, cumpliendo estrictamente con los lineamientos de seguridad de OATI.
-Conformidad: Ideal para entornos donde se requiere alta conformidad regulatoria y donde los datos sensibles deben permanecer en la red interna.
-Costos a Largo Plazo: Aunque los costos iniciales son altos, puede ser más económico a largo plazo si la demanda es constante.
-Se cuenta con servidor dedicado propio. 

No:
-Escalabilidad Limitada: Aumentar la capacidad requiere inversión en hardware.
-Mantenimiento: Requiere gestión continua, lo que puede ser un desafío operativo.

**Comment by a52290451** [comment]
De acuerdo con lo conversado con Infraestructura y DBAs, la mejor opción es utilizar serverless para acceder a la base de datos.
