### ISSUE TITLE
Creación de API plantillas_mid

### ISSUE THREAD

**Issue by a52290451** [udistrital/plantillas_cliente#4]
Se requiere crear en su forma base el API plantillas_mid para el modulo de plantillas.

**Especificaciones técnicas**

- El repositorio del API es: https://github.com/udistrital/plantillas_mid

**Sub Tareas**

- [x] Creación y ajuste del repositorio.
- [x] Creación de API en local, con estructura base de API MID (tomar como referencia el API cumplidos_dve_mid en sus primeros commits).
- [x] Aplicación de lineamientos para creación de API MID.

**Criterios de aceptación**

- [x] El API se encuentra creada en su estructura base y responde con un 200 en las peticiones realizadas al healtcheck.
- [x] El API cumple con los [lineamientos](https://github.com/udistrital/lineamientos_oas) dispuestos para la creación de un API MID.

**Requerimientos**

- [x] El repositorio plantillas_mid debe estar creado.

**Dependencias**

- No presenta

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by milo19980525** [comment]
@Yaov05 Por favor documentar el issue.

**Comment by Yaov05** [comment]
Primer commit del api de plantillas_mid
https://github.com/udistrital/plantillas_mid/commit/1127adc494ce02c343f0494e94b31fa48e409948

**Comment by milo19980525** [comment]
@Yaov05 se compromete a tener los routers para hoy.

**Comment by Yaov05** [comment]
Commit con commentsRouter y controlador para secciones, minutas y titulos:
https://github.com/udistrital/plantillas_mid/commit/b0003ab7af59b4f5af35257ff4640d6a05dba6ad#diff-b9cafd76ba69db1e1ba8d7805a08aab1cfde3280140154fdf4764b2f6dc0ab85
