### ISSUE TITLE
Construcción plantillas CRUD Parte 2

### ISSUE THREAD

**Issue by a52290451** [udistrital/plantillas_cliente#44]
Se debe continuar con la construcción del CRUD de plantillas empleando el concepto serverless, de acuerdo con la investigación realizada en udistrital/plantillas_cliente#38 .

**Especificaciones Técnicas**

- Se debe continuar con la investigación de serverless y, con las credenciales correspondientes, se requiere iniciar el proceso de construcción del CRUD  de plantillas en AWS, mediante lambdas.
- Se debe tomar como referencia de desarrollo el repositorio https://github.com/udistrital/prueba_piloto_funciones_lambda.

**Sub Tareas**

- [x] Implementación del Crud de Plantillas en serverless.

**Criterios de aceptación**

- [x] El CRUD de PLANTILLAS se encuentra implementado en serverless mediante lambdas en AWS.

**Requerimientos**

- Completar issue udistrital/plantillas_cliente#38 .
- Capacitación Serverless con Heiner.

**Dependencias**

- plantillas_mid.
- BD Plantillas.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Se realiza ajuste para el modelo de datos de plantillas_crud, quedando de la siguiente manera: 

![plantillas_crud](https://github.com/user-attachments/assets/a09278b3-1ab0-409d-ac09-1dff84579d22)

**Comment by diegobauto** [comment]
Se realiza ajuste al valor uid como string: 
![plantillas_crud](https://github.com/user-attachments/assets/e8494bb6-deeb-4762-9d5f-a1602714e37a)

**Comment by diegobauto** [comment]
Se asocia desarrollo del API con SAM, alojado en la rama de plantillas_crud: [feature/serverless](https://github.com/udistrital/plantillas_crud/tree/feature/serverless)
Estado: En progreso

**Comment by diegobauto** [comment]
Se culmina desarrollo del API de plantillas_crud:

- Evidencia registro [post] y obtencion [get] de platilla:

[Grabación de pantalla desde 31-08-24 17:34:20.webm](https://github.com/user-attachments/assets/8cc7e73e-909f-4ec2-869f-09bfc3e58e07)

- Evidencia registro [post] y obtencion [get] de tipo_plantilla:

[Grabación de pantalla desde 31-08-24 17:35:30.webm](https://github.com/user-attachments/assets/84368903-0b9c-43cc-8f74-f983f10f831d)

- De igual manera se realizan pruebas funcionales evidenciando los diferentes métodos para cada una de las colecciones:
[Pruebas funcionales - API Plantillas](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EYo4P3FdaJ5Bv37zf57H3g4Bc7OOXvM0PlcC-26WDYtZ0A?e=Gw0g7o)

**Comment by a52290451** [comment]
Se requiere subir PR a plantillas_crud_serverless

**Comment by diegobauto** [comment]
Pull request: https://github.com/udistrital/plantillas_crud_serverless/pull/1

**Comment by diegobauto** [comment]
Modelo de datos: 

![plantillas_crud](https://github.com/user-attachments/assets/f03ce7b6-c319-4f02-83fb-19d92531f718)

**Comment by a52290451** [comment]
Se da cierre a la tarea y se continua en udistrital/plantillas_cliente#45 .
