### ISSUE TITLE
Adaptación Modulo dinámico para creación de plantillas en plantillas_cliente

### ISSUE THREAD

**Issue by a52290451** [udistrital/plantillas_cliente#47]
De acuerdo con la investigación realizada en udistrital/plantillas_cliente#42 , se requiere llevar a cabo la implementación de uno de estos modulos en plantillas_cliente, de tal forma que se permita la creación dinámica de plantillas con un editor especializado. La información que se genera, debe poder accederse y almacenarse en la Base de datos de plantillas_crud.

**Especificaciones técnicas**

- El Editor dinámico para plantillas debe ser de código abierto.
- Deben poderse realizar cambios en el editor para añadir y leer elementos dinámicos.
- La información relacionada a la plantilla, generada por el editor debe almacenarse en el modelo de datos de plantillas.
- Deben consumirse los métodos requeridos en plantillas_mid para almacenar y gestionar la información correctamente.
- El editor de plantillas debe estar incrustado en la vista "Creación de plantillas" y debe estar relacionado con "creación" y "edición".
- Añadir campos complementarios al editor de plantillas y necesarios para el modelo de datos de plantillas  en "Creación de plantillas".

**Sub Tareas**

- [x] Incrustación de editor de plantillas en "creación de plantillas".
- [x] Añadir y relacionar campos complementarios en "creación de plantillas".
- [x] Enlace de información del editor con el modelo de plantillas a través de plantillas_mid.
- [x] Relación de "creación de plantillas" con "creación" y "edición".

**Criterios de aceptación**

- [x] El editor de plantillas permite crear cualquier tipo de plantilla a través del editor incrustado.
- [x] La información de plantillas se almacena de forma correcta en el modelo de datos y puede se recuperada esta información para mostrarse en el cliente.

**Requerimientos**

- [x] Completar definición de Editor para ser utilizado en plantillas en udistrital/plantillas_cliente#42 .

**Dependencias**

- plantillas_mid
- plantillas_clientes
- plantillas_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Carga inicial creación de plantillas: 
![image](https://github.com/user-attachments/assets/059b7f84-fc7c-41c0-85cd-afb762e08c10)

**Comment by a52290451** [comment]
Añadir pruebas funcionales

**Comment by a52290451** [comment]
incluir pruebas funcionales y enviar PR @diegobauto

**Comment by diegobauto** [comment]
- Pruebas funcionales:

Inserción de campo dinamico y visualización del mismo como contenido HTML:

[Grabación de pantalla desde 14-09-24 15:57:01.webm](https://github.com/user-attachments/assets/959b58f2-4371-4f21-9854-ff097c2e32d6)


Carga inicial componente creación de plantillas:

[Grabación de pantalla desde 16-09-24 18:17:42.webm](https://github.com/user-attachments/assets/9b7f1df6-3493-49b3-823b-99f1dc5a7136)

**Comment by diegobauto** [comment]
> incluir pruebas funcionales y enviar PR @diegobauto

Ya se realizó el merge:
![image](https://github.com/user-attachments/assets/f3c964a4-d5e2-412b-b240-bde3785b567b)
