### ISSUE TITLE
Creación de cliente del módulo de plantillas

### ISSUE THREAD

**Issue by a52290451** [udistrital/plantillas_cliente#5]
Se requiere crear en su forma base el Cliente del módulo de plantillas, empleando nuevas tecnologías.

**Especificaciones técnicas**

- El repositorio del cliente es: https://github.com/udistrital/plantillas_cliente

**Sub Tareas**

- [x] Creación y ajuste del repositorio.
- [x] Creación del cliente en local, con estructura base de nuevos clientes (tomar como referencia el cliente cumplidos_dve_cliente en sus primeros commits).
- [x] Diseño de logotipo y banners para el módulo de plantillas.
- [x] Adecuación del cliente a las necesidades del modulo de plantillas en cuanto a paleta de colores, logotipos, banners y consumo de web-components para el concepto de la interfaz relacionado con lo dispuesto por la OAS.
- [x] Aplicación de lineamientos para creación de clientes.

**Criterios de aceptación**

- [x] El cliente se encuentra creado y presenta todos los elementos asociados al modulo de plantillas en cuanto a paleta de colores, logotipos, banners e interfaz gráfica estándar.
- [x] El cliente cumple con los [lineamientos](https://github.com/udistrital/lineamientos_oas) dispuestos para la creación de un cliente en nuevas tecnologías.

**Requerimientos**

- [x] El repositorio plantillas_cliente debe estar creado.

**Dependencias**

- Web-components

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by milo19980525** [comment]
@Yaov05 se compromete a tener el banner y el logo para mañana 19/09/23.

**Comment by Yaov05** [comment]
[Logotipo.pdf](https://github.com/udistrital/plantillas_cliente/files/12669914/Logotipo.pdf)
 En el archivo hay algunas propuestas del isotipo para el módulo. El banner en la interfaz no se muestra aún, debido a un problema de ejecución del cliente en local.

**Comment by milo19980525** [comment]
@Yaov05 Gracias por la variedad de logos creados. Se determina junto con el Gerente de proyectos que la opción más agradable a la vista es la primera: 
![MicrosoftTeams-image](https://github.com/udistrital/plantillas_cliente/assets/106636533/a05efdf8-3f98-41f5-86c8-88e6f373efcd)

**Comment by milo19980525** [comment]
@Yaov05 subir los cambios al repositorio y documentar evidencias en el issue.

**Comment by Yaov05** [comment]
Primer commit al repositorio del cliente: https://github.com/udistrital/plantillas_cliente/commit/0c1b6f2399326da55bfc9316c61adb6685507fea

**Comment by milo19980525** [comment]
@Yaov05 Documentar las evidencias de ejecución en local.

**Comment by Yaov05** [comment]
Actualmente el sistema cuenta con el módulo para iniciar sesión por medio de web-components, hace falta agregar el logotipo e isotipo de plantillas al repo https://github.com/udistrital/assets en formato svg para su uso en la página

![image](https://github.com/udistrital/plantillas_cliente/assets/42217637/e6153f1b-92c2-4261-ac7b-9515c750f90b)

![image](https://github.com/udistrital/plantillas_cliente/assets/42217637/de8defd2-df6b-404a-ad68-b0776a220899)

A la derecha de la imagen se puede ver la petición

![image](https://github.com/udistrital/plantillas_cliente/assets/42217637/5daeba92-2374-4b6a-b099-637ebdd8ef84)

**Comment by Yaov05** [comment]
Actualmente el cliente cuenta con web-components para el inicio de sesión. Hace falta agregar el logotipo e isotipo al repo https://github.com/udistrital/assets para ser consultados.

![image](https://github.com/udistrital/plantillas_cliente/assets/42217637/e6153f1b-92c2-4261-ac7b-9515c750f90b)

![image](https://github.com/udistrital/plantillas_cliente/assets/42217637/50b94c0c-4a84-4572-8eb6-8f57b1b277de)

A la derecha se puede ver la petición para obtener el logotipo en formato svg

![image](https://github.com/udistrital/plantillas_cliente/assets/42217637/318eb951-bbaf-4caa-a201-f6b91e3d1ee6)
