### ISSUE TITLE
Lineamiento Serverless

### ISSUE THREAD

**Issue by a52290451** [udistrital/plantillas_cliente#52]
Se requiere realizar el documento técnico relacionado con la implementación de serverless a nivel general y como caso aplicado en plantillas_crud.

**Especificaciones Técnicas**

- Se trata de un documento técnico que describe los aspectos principales de la tecnologia implementada y un paso a paso de como realizar la configuración he implementación del mismo.
- Se debe documentar cada aspecto fundamental del proceso, desde su desarrollo en local hasta su configuración en AWS.
- Se debe utilizar como caso de ejemplo la implementación de plantillas_crud.
- Utilizar como guia para el documento técnico el realizado en udistrital/planeacion_cliente#1284 .
- Adicionalmente, se debe incluir como lineamiento la guia y el paso a paso de como implementar la tecnología en el [repositorio de lineamientos](https://github.com/udistrital/lineamientos_oas).

**Sub Tareas**

- [x] Documento técnico Serverless.
- [x] Lineamientos Serverless.

**Criterios de aceptación**

- [x] Se presenta un documento técnico detallado con todos los aspectos principales de serverless.
- [x] Se incluye el paso a paso de implementación en lineamientos.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by diegobauto** [comment]
Creación y avance de documentación Serverless: [Documento Lineamiento Serverless](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EQ-h7Rw3RkJFgPpLQeiTGjgBm69nNWjrft74Ztz-q-XHUQ?e=7JcYsL)

**Comment by diegobauto** [comment]
Se da por finalizado el documento técnico para serverless:
[Documento Lineamiento Serverless](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EQ-h7Rw3RkJFgPpLQeiTGjgBm69nNWjrft74Ztz-q-XHUQ?e=7JcYsL)

**Comment by diegobauto** [comment]
Se añaden lineamientos a [lineamientos_oas](https://github.com/udistrital/lineamientos_oas).

Link del pull request: 
https://github.com/udistrital/lineamientos_oas/pull/72
