### ISSUE TITLE
Apropiación de generalidades

### ISSUE THREAD

**Issue by a52290451** [udistrital/plantillas_cliente#7]
Se requiere realizar las siguientes actividades para completar el proceso de inducción a los sistemas de la OAS y apropiación de generalidades:

1. Estudio de lineamientos.
2. Instalación y ejecución del API cumplidos_dve_mid en local.
3. Instalación y ejecución del API cumplidos_dve_crud en local.
4. Instalación y ejecución del API cumplidos_dve_cliente en local.
5. conexión entre apis a nivel local.
6. prueba de funcionalidades a través del cliente en local.
7. Revisión de diagrama de actividades para el módulo de plantillas.
8. Revisión de HUs de usuario para el módulo de plantillas.

**Especificaciones técnicas**

- El repositorio de cumplidos_dve_mid es: https://github.com/udistrital/cumplidos_dve_mid
- El repositorio de cumplidos_dve_crud es: https://github.com/udistrital/cumplidos_dve_crud
- El respositorio de cumplidos_dve_cliente es: https://github.com/udistrital/cumplidos_dve_cliente
- Los lineamientos de la OAS son: https://github.com/udistrital/lineamientos_oas/tree/master

Nota:
1. La clonación de las APIs y el cliente debe hacerse desde la rama Develop de cada repositorio.
2. Los valores de las variables de entorno requeridas para ejecutar las APIs en local se adjuntan como comentarios en este issue.
3. Para ejecutar cada API y el cliente, se deben seguir los pasos señalados en el readme de cada repositorio asociado.
4. En los comentarios se adjuntan usuarios de prueba para probar el sistema en local.

**Sub Tareas**

- [x] Estudio de lineamientos.
- [x] Instalación y ejecución del API cumplidos_dve_mid en local.
- [x] Instalación y ejecución del API cumplidos_dve_crud en local.
- [x] Instalación y ejecución del API cumplidos_dve_cliente en local.
- [x] conexión entre apis a nivel local.
- [x] prueba de funcionalidades a través del cliente en local.
- [x] Revisión de diagrama de actividades para el módulo de plantillas.
- [x] Revisión de HUs de usuario para el módulo de plantillas.

**Criterios de aceptación**

- [x] El desarrollador entiende los lineamientos asociados a todos los elementos que conforman los sistemas de la OAS.
- [x] Las APIs señaladas funcionan correctamente en local y es posible consultar información a través de sus servicios.
- [x] Las funcionalidades del sistema en general pueden ser probadas a través del cliente.

**Requerimientos**

- [x] VPN
- [x] Usuarios de prueba
- [x] Variables de entorno

**Dependencias**

- No presenta

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

Material de apoyo:

1. [Diagrama de flujo de actividades módulo de plantillas](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/Efy5WGMmwD5IuF9GaqgSIEEBJ1nBFtnJmJM5NnpmCmZiIw?e=vcm3J4)
2. [Historias de usuario - Modulo de plantillas](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EZI5GpJBXzpBg2jWJvIXHKAB4p7h2UtQi0Uq0EylrnUo4g?e=r8V8zL)
3. [Inventario de APIs](https://docs.google.com/spreadsheets/d/15vnSFpfyOaf8dWfvG9h4EHmlf2bKOUSYSxydrafyqLU/edit?usp=sharing)
4. [API Store WSO2 - API Gateway](https://autenticacion.portaloas.udistrital.edu.co/store/apis/list?query=&tenant=carbon.super)
5. [Api Configuracion](https://pruebasconfiguracion.portaloas.udistrital.edu.co/)

**Comment by a52290451** [comment]
Los usuarios de prueba para el sistema se envian por interno

**Comment by a52290451** [comment]
Variables MID:

export CUMPLIDOS_DVE_MID_HTTP_PORT=9001
export CUMPLIDOS_DVE_MID_GESTOR_DOCUMENTAL_URL=http://pruebasapi2.intranetoas.udistrital.edu.co:8199/v1/
export CUMPLIDOS_DVE_MID_CORE_URL=http://api.intranetoas.udistrital.edu.co:8106/v1/
export CUMPLIDOS_DVE_MID_OIKOS_URL=http://pruebasapi.intranetoas.udistrital.edu.co:8087/v2/
export CUMPLIDOS_DVE_MID_PARAMETROS_URL=http://pruebasapi.intranetoas.udistrital.edu.co:8510/v1/
export CUMPLIDOS_DVE_MID_WSO2_URL=http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/
export CUMPLIDOS_DVE_MID_ADMINISTRATIVA_JBPM=administrativa_produccion
export CUMPLIDOS_DVE_MID_HOMOLOGACION_JBPM=servicios_homologacion_dependencias
export CUMPLIDOS_DVE_MID_ACADEMICA_JBPM=academica_pruebas
export CUMPLIDOS_DVE_MID_FINANCIERA_JBPM=financiera_produccion
export CUMPLIDOS_DVE_MID_AGORA_URL=http://pruebasapi.intranetoas.udistrital.edu.co:8104/v1/
export CUMPLIDOS_DVE_MID_ADMIN_URL=http://pruebasapi.intranetoas.udistrital.edu.co:8090/v1/
export CUMPLIDOS_DVE_CRUD_URL=http://pruebasapi2.intranetoas.udistrital.edu.co:8534/v1/
export CUMPLIDOS_DVE_CRUD_RESOLUCIONES_URL=http://pruebasapi2.intranetoas.udistrital.edu.co:8528/v1/
export CUMPLIDOS_DVE_MID_STATIC_PATH=static bee run
export CUMPLIDOS_DVE_MID_TITAN_URL=http://pruebasapi.intranetoas.udistrital.edu.co:8082/v1/

**Comment by a52290451** [comment]
Variables CRUD:

export CUMPLIDOS_DVE_CRUD_HTTP_PORT=9002
export CUMPLIDOS_DVE_CRUD_PGUSER= XXXX
export CUMPLIDOS_DVE_CRUD_PGPASS= XXXX
export CUMPLIDOS_DVE_CRUD_PGHOST=pgtst.udistritaloas.edu.co
export CUMPLIDOS_DVE_CRUD_PGPORT=5432
export CUMPLIDOS_DVE_CRUD_PGDB=udistrital_administrativa
export CUMPLIDOS_DVE_CRUD_PGSCHEMA=cumplidos_dve

**Comment by siexud** [comment]
Se realizarón pruebas de instalación y despliegue en servidor linux con Ubuntu server sin poder acceder al front de la aplicación. Por lo tanto, se realizarón los pasos de instalación en ambiente local en Windows y se probaron sus funcionalidades para diferentes usuarios.
![Captura](https://github.com/udistrital/plantillas_cliente/assets/102606989/f494f9d2-8a12-463b-8f18-d6c5d295f407)
