### ISSUE TITLE
Investigación de componente externo para creación y edición de plantillas

### ISSUE THREAD

**Issue by a52290451** [udistrital/plantillas_cliente#8]
Se requiere investigar la existencia de componentes externos a los dispuestos por la OAS para la creación dinámica de documentos, que puedan ser utilizados para la vista "creación/edición de plantillas". El componente debe cumplir con los siguientes requerimientos:

1. Inserción de campos de escritura.
2. Inserción de títulos.
3. Inserción de imágenes.
4. Modificación del orden de los elementos insertados.
5. Modificación de estilos de los elementos insertados.
6. Eliminar elementos insertados.
7. Inserción de campos dinámicos.

**Especificaciones técnicas**

- El componente debe poder ser incrustado en la vista "creación/edición de plantillas" para su utilización o, en su defecto, ser consumido por el módulo de plantillas, con intercambio de información a través de API REST.

**Sub Tareas**

- [x] Investigación de posibles alternativas de componentes externos para la vista "creación/edición de plantillas".

**Criterios de aceptación**

- [x] Se presentan posibles alternativas a ser empleadas en la vista "creación/edición de plantillas" para la construcción dinámica de plantillas.

**Requerimientos**

- No presenta

**Dependencias**

- No presenta

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

Material de apoyo:

1. [Diagrama de flujo de actividades módulo de plantillas](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/Efy5WGMmwD5IuF9GaqgSIEEBJ1nBFtnJmJM5NnpmCmZiIw?e=vcm3J4)
2. [Historias de usuario - Modulo de plantillas](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EZI5GpJBXzpBg2jWJvIXHKAB4p7h2UtQi0Uq0EylrnUo4g?e=r8V8zL)

**Comment by siexud** [comment]
Se presenta la propuesta de crear el módulo de creación de plantillas utilizando:

### frontend
*  Angular forms para la generación de campos de ingreso dinámicos
### traductor de plantillas
*  [template package](https://pkg.go.dev/text/template/) para renderizar textos de forma dinámica
* [go-gin](https://gin-gonic.com/) renderizar html de forma dinámica

**Comment by Yaov05** [comment]
Una de las herramientas que pueden ser útiles es ReportLab, una biblioteca específica para crear documentos PDF, con la capacidad para añadir texto, imágenes, tablas, gráficos, entre otras cosas

Tiene un enfoque en documentos estructurados y profesionales y sirve para crear documentos complejos como informes.

Tiene varias ventajas, como el nivel de control que se tiene sobre el diseño y la apariencia del documento. Se puede especificar muchas variables como la posición y el estilo de los elementos en el PDF.
Otra, es la facilidad para añadir imágenes, con respecto a otras herramientas.

Se había considerado otros componentes como FPDF(PHP), iText(Java/.NET), wkhtmltopdf(HTML y CSS). Sin embargo, estos se quedan atrás en cuanto a complejidad. La facilidad de ReportLab para crear documentos más complejos termina siendo ventajoso.

**Comment by Yaov05** [comment]
Para generar textos de forma dinámica, Go templates es una buena opción, por lo que, en primera medida, se proponen dos maneras de desarrollo el módulo de plantillas:

Utilizar Go templates para el proceso de generación de documentos y traducción de plantillas.

Utilizar en conjunto Go templates y ReportLab para generar de manera dinámica los documentos.


En cuanto al frontend, se pretende analizar la mejor opción, con Angular moderno (Typescript) y Vue.js como las más adecuadas de momento.



Actualización:

Para el frontend, se opta por usar Angular moderno (typescript) para la creación de campos de ingreso dinámicos a través de angular forms, descartando la posibilidad de usar Vue.js, que es un framework más útil para aplicaciones sencillas, y Angular javascript, que desde junio de 2022 dejó de tener soporte oficial por Google, quien envía actualizaciones para Angular typescript más frecuentemente, pero sin que esto signifique que todo el tiempo haya que cambiar dependencias
