### ISSUE TITLE
Creación de CRUD de plantillas con serverless

### ISSUE THREAD

**Issue by milo19980525** [udistrital/plantillas_cliente#9]
Se requiere crear en su forma base el API plantillas_crud para el modulo de plantillas  teniendo en cuenta la implementación serverless.

**Especificaciones técnicas**

- El repositorio del API es: https://github.com/udistrital/plantillas_crud_serverless
- Se debe guiar del repositorio: https://github.com/udistrital/prueba_piloto_funciones_lambda
- Se neceita instalación de AWS SAM.

**Sub Tareas**

- [x] Creación y ajuste del repositorio.
- [x] Creación de API en local, con estructura base de API CRUD Serverless.
- [x] Adecuación de API CRUD para conectar con la BD de plantillas.
- [x] Aplicación de lineamientos para creación de API CRUD.

**Criterios de aceptación**

- [x] El API se encuentra creada y contiene todos los controladores requeridos para conectar con la BD.
- [x] El API cumple con los [lineamientos](https://github.com/udistrital/lineamientos_oas) dispuestos para la creación de un API CRUD.

**Requerimientos**

- [x] EL issue #2 , debe estar terminado.
- [x] El repositorio plantillas_crud_serverless debe estar creado.

**Dependencias**

- No presenta

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder té

**Comment by milo19980525** [comment]
Se solicitaron permisos correspondientes el día viernes: https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=56088&group_id=116

**Comment by milo19980525** [comment]
Se crea BD https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=56136&group_id=177

**Comment by milo19980525** [comment]
@Yaov05 subir los cambios al repositorio y documentar evidencias en el issue.

**Comment by Yaov05** [comment]
Primeros commits al repositorio de plantillas_crud_serverless:
https://github.com/udistrital/plantillas_crud_serverless/commit/08fdda3e65771cb54f697802b37ca00cd72295f0
https://github.com/udistrital/plantillas_crud_serverless/commit/0b92f2eb45f763e770e43a71383581123d0c7351

**Comment by milo19980525** [comment]
@Yaov05 Documentar las evidencias de ejecución en local.

**Comment by Yaov05** [comment]
El crud se ejecuta en local para invocar los handlers de las funciones lambda montadas en un container local en docker
![image](https://github.com/udistrital/plantillas_cliente/assets/42217637/4a1fb388-495f-4116-8116-b3fd3ca53269)

![image](https://github.com/udistrital/plantillas_cliente/assets/42217637/46b3a916-cdd0-4f59-a671-2ee0d5899247)
